export const ORDERS_ADD_REQUEST = "ORDERS_ADD_REQUEST";
export const ORDERS_ADD_SUCCESS = "ORDERS_ADD_SUCCESS";
export const ORDERS_ADD_FAIL = "ORDERS_ADD_FAIL";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";
