export const PAYEMENT_METHOD_REQUEST = "PAYEMENT_METHOD_REQUEST";
export const PAYEMENT_METHOD_SUCCESS = "PAYEMENT_METHOD_SUCCESS";
export const PAYEMENT_METHOD_FAIL = "PAYEMENT_METHOD_FAIL";
export const SAVE_PAYEMENT_METHOD = "SAVE_PAYEMENT_METHOD";
